function proposals_module(){var P='',wb='" for "gwt:onLoadErrorFn"',ub='" for "gwt:onPropertyErrorFn"',ib='"><\/script>',Z='#',Eb='&',nc='.cache.html',_='/',Mb='10FFBF76756F4B9B43582D5C398C0A0E',Ob='30245A73D362E98FB276DB1E833D8EB8',Qb='435A3605492418B02EF5FA4E0E63465E',Sb='49828D6D300092269119B8027ACB14FC',Ub='4FAA20D1A4B26390CF0C5AA34263FC0C',Wb='52FC3A4B312BF6BCF3382CE858DBBE1F',Xb='5FE4A874E4F868D3E101CB8455373487',Zb='6B5A46273FAD7D3A4D39524088DFEB34',_b='82E7E96B84677EC2D219268F04C15660',mc=':',ob='::',wc='<script defer="defer">proposals_module.onInjectionDone(\'proposals_module\')<\/script>',hb='<script id="',rb='=',$='?',bc='AA304E85AF0CC259DF16A094BA6EC886',dc='BBE93C242B8DE1645A21C5E71B099764',tb='Bad handler "',fc='D6F205BAC5DADCEBCA7F3B4133A752AA',vc='DOMContentLoaded',uc='DatePickerStyle.css',hc='F20646651A5A85B486E5571AA84CD6FC',jc='F3BF411C64D8BF5841A05744E9C6F8D9',lc='FFA9889A15ED2733A79CB75CCA5B4317',jb='SCRIPT',Hb='Unexpected exception in locale detection, using default: ',Gb='_',Fb='__gwt_Locale',gb='__gwt_marker_proposals_module',kb='base',cb='baseUrl',T='begin',S='bootstrap',bb='clear.cache.gif',qb='content',ic='de_CH',gc='de_DE',Cb='default',ec='en_GB',ac='en_UK',Y='end',Tb='fr',Lb='fr_CA',cc='fr_CH',Nb='fr_FR',U='gwt.codesvr=',V='gwt.hosted=',W='gwt.hybrid',oc='gwt/standard/standard.css',vb='gwt:onLoadErrorFn',sb='gwt:onPropertyErrorFn',pb='gwt:property',tc='head',Jb='hosted.html?proposals_module',sc='href',Vb='hu_HU',xb='iframe',ab='img',Pb='it_CH',Yb='it_IT',yb="javascript:''",pc='link',Ib='loadExternalRefs',Bb='locale',Db='locale=',lb='meta',Ab='moduleRequested',X='moduleStartup',mb='name',Rb='pl_PL',zb='position:absolute;width:0;height:0;border:none',Q='proposals_module',eb='proposals_module.nocache.js',nb='proposals_module::',kc='pt_BR',$b='pt_PT',qc='rel',db='script',Kb='selectingPermutation',R='startup',rc='stylesheet',fb='undefined';var l=window,m=document,n=l.__gwtStatsEvent?function(a){return l.__gwtStatsEvent(a)}:null,o=l.__gwtStatsSessionId?l.__gwtStatsSessionId:null,p,q,r,s=P,t={},u=[],v=[],w=[],x=0,y,z;n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:T});if(!l.__gwt_stylesLoaded){l.__gwt_stylesLoaded={}}if(!l.__gwt_scriptsLoaded){l.__gwt_scriptsLoaded={}}function A(){var b=false;try{var c=l.location.search;return (c.indexOf(U)!=-1||(c.indexOf(V)!=-1||l.external&&l.external.gwtOnLoad))&&c.indexOf(W)==-1}catch(a){}A=function(){return b};return b}
function B(){if(p&&q){var b=m.getElementById(Q);var c=b.contentWindow;if(A()){c.__gwt_getProperty=function(a){return H(a)}}proposals_module=null;c.gwtOnLoad(y,Q,s,x);n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:X,millis:(new Date).getTime(),type:Y})}}
function C(){function e(a){var b=a.lastIndexOf(Z);if(b==-1){b=a.length}var c=a.indexOf($);if(c==-1){c=a.length}var d=a.lastIndexOf(_,Math.min(c,b));return d>=0?a.substring(0,d+1):P}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=m.createElement(ab);b.src=a+bb;a=e(b.src)}return a}
function g(){var a=F(cb);if(a!=null){return a}return P}
function h(){var a=m.getElementsByTagName(db);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(eb)!=-1){return e(a[b].src)}}return P}
function i(){var a;if(typeof isBodyLoaded==fb||!isBodyLoaded()){var b=gb;var c;m.write(hb+b+ib);c=m.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=jb){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return P}
function j(){var a=m.getElementsByTagName(kb);if(a.length>0){return a[a.length-1].href}return P}
var k=g();if(k==P){k=h()}if(k==P){k=i()}if(k==P){k=j()}if(k==P){k=e(m.location.href)}k=f(k);s=k;return k}
function D(){var b=document.getElementsByTagName(lb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(mb),g;if(f){f=f.replace(nb,P);if(f.indexOf(ob)>=0){continue}if(f==pb){g=e.getAttribute(qb);if(g){var h,i=g.indexOf(rb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=P}t[f]=h}}else if(f==sb){g=e.getAttribute(qb);if(g){try{z=eval(g)}catch(a){alert(tb+g+ub)}}}else if(f==vb){g=e.getAttribute(qb);if(g){try{y=eval(g)}catch(a){alert(tb+g+wb)}}}}}}
function E(a,b){return b in u[a]}
function F(a){var b=t[a];return b==null?null:b}
function G(a,b){var c=w;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
function H(a){var b=v[a](),c=u[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(z){z(a,d,b)}throw null}
var I;function J(){if(!I){I=true;var a=m.createElement(xb);a.src=yb;a.id=Q;a.style.cssText=zb;a.tabIndex=-1;m.body.appendChild(a);n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:X,millis:(new Date).getTime(),type:Ab});a.contentWindow.location.replace(s+L)}}
v[Bb]=function(){var b=null;var c=Cb;try{if(!b){var d=location.search;var e=d.indexOf(Db);if(e>=0){var f=d.substring(e+7);var g=d.indexOf(Eb,e);if(g<0){g=d.length}b=d.substring(e+7,g)}}if(!b){b=F(Bb)}if(!b){b=l[Fb]}if(b){c=b}while(b&&!E(Bb,b)){var h=b.lastIndexOf(Gb);if(h<0){b=null;break}b=b.substring(0,h)}}catch(a){alert(Hb+a)}l[Fb]=c;return b||Cb};u[Bb]={de_CH:0,de_DE:1,'default':2,en_GB:3,en_UK:4,fr:5,fr_CA:6,fr_CH:7,fr_FR:8,hu_HU:9,it_CH:10,it_IT:11,pl_PL:12,pt_BR:13,pt_PT:14};proposals_module.onScriptLoad=function(){if(I){q=true;B()}};proposals_module.onInjectionDone=function(){p=true;n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:Ib,millis:(new Date).getTime(),type:Y});B()};D();C();var K;var L;if(A()){if(l.external&&(l.external.initModule&&l.external.initModule(Q))){l.location.reload();return}L=Jb;K=P}n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:Kb});if(!A()){try{G([Lb],Mb);G([Nb],Ob);G([Pb],Qb);G([Rb],Sb);G([Tb],Ub);G([Vb],Wb);G([Cb],Xb);G([Yb],Zb);G([$b],_b);G([ac],bc);G([cc],dc);G([ec],fc);G([gc],hc);G([ic],jc);G([kc],lc);K=w[H(Bb)];var M=K.indexOf(mc);if(M!=-1){x=Number(K.substring(M+1));K=K.substring(0,M)}L=K+nc}catch(a){return}}var N;function O(){if(!r){r=true;if(!__gwt_stylesLoaded[oc]){var a=m.createElement(pc);__gwt_stylesLoaded[oc]=a;a.setAttribute(qc,rc);a.setAttribute(sc,s+oc);m.getElementsByTagName(tc)[0].appendChild(a)}if(!__gwt_stylesLoaded[uc]){var a=m.createElement(pc);__gwt_stylesLoaded[uc]=a;a.setAttribute(qc,rc);a.setAttribute(sc,s+uc);m.getElementsByTagName(tc)[0].appendChild(a)}B();if(m.removeEventListener){m.removeEventListener(vc,O,false)}if(N){clearInterval(N)}}}
if(m.addEventListener){m.addEventListener(vc,function(){J();O()},false)}var N=setInterval(function(){if(/loaded|complete/.test(m.readyState)){J();O()}},50);n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:Y});n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:Ib,millis:(new Date).getTime(),type:T});m.write(wc)}
proposals_module();