function proposals_module(){var P='',wb='" for "gwt:onLoadErrorFn"',ub='" for "gwt:onPropertyErrorFn"',ib='"><\/script>',Z='#',Eb='&',nc='.cache.html',_='/',Mb='0BE48BB71962B6600134B4273B3912AA',Ob='0E048F452AE53F77E5DF7CABF5FDC146',Pb='0FCE38790BD9587987AAAE549430E562',Rb='38611C0021543643E0969555D78FD53D',Tb='3A70C6D508196A1B6F8FF7C04A8C1C5D',Vb='446CF08165D0415A37AA250D6A0167B9',Xb='84FE2A1400C46D9A18941411F6C50463',mc=':',ob='::',wc='<script defer="defer">proposals_module.onInjectionDone(\'proposals_module\')<\/script>',hb='<script id="',rb='=',$='?',Zb='A62534757C3765A01FA13F88F6D9498E',_b='A742E1C5B13C396F271B024B223DACF4',bc='A8B27008BBFFA7F7D45E9A930F45A9B2',dc='BA0F3C47EFDC99556072AD3F66272B1E',tb='Bad handler "',fc='C7BD1B16C4FA17FB3DA3A2840A155ECF',hc='CA0011AE4212A3ACC22B30BB4D50F989',jc='DEAA7878DDF74F3B761A27207A7B6AF5',vc='DOMContentLoaded',uc='DatePickerStyle.css',lc='E3E76AA88AF0A57B881CD0BBB6A105F1',jb='SCRIPT',Hb='Unexpected exception in locale detection, using default: ',Gb='_',Fb='__gwt_Locale',gb='__gwt_marker_proposals_module',kb='base',cb='baseUrl',T='begin',S='bootstrap',bb='clear.cache.gif',qb='content',Lb='de_CH',ac='de_DE',Cb='default',Ub='en_GB',Sb='en_UK',Y='end',Yb='fr',cc='fr_CA',Nb='fr_CH',kc='fr_FR',U='gwt.codesvr=',V='gwt.hosted=',W='gwt.hybrid',oc='gwt/standard/standard.css',vb='gwt:onLoadErrorFn',sb='gwt:onPropertyErrorFn',pb='gwt:property',tc='head',Jb='hosted.html?proposals_module',sc='href',Wb='hu_HU',xb='iframe',ab='img',gc='it_CH',ec='it_IT',yb="javascript:''",pc='link',Ib='loadExternalRefs',Bb='locale',Db='locale=',lb='meta',Ab='moduleRequested',X='moduleStartup',mb='name',Qb='pl_PL',zb='position:absolute;width:0;height:0;border:none',Q='proposals_module',eb='proposals_module.nocache.js',nb='proposals_module::',$b='pt_BR',ic='pt_PT',qc='rel',db='script',Kb='selectingPermutation',R='startup',rc='stylesheet',fb='undefined';var l=window,m=document,n=l.__gwtStatsEvent?function(a){return l.__gwtStatsEvent(a)}:null,o=l.__gwtStatsSessionId?l.__gwtStatsSessionId:null,p,q,r,s=P,t={},u=[],v=[],w=[],x=0,y,z;n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:T});if(!l.__gwt_stylesLoaded){l.__gwt_stylesLoaded={}}if(!l.__gwt_scriptsLoaded){l.__gwt_scriptsLoaded={}}function A(){var b=false;try{var c=l.location.search;return (c.indexOf(U)!=-1||(c.indexOf(V)!=-1||l.external&&l.external.gwtOnLoad))&&c.indexOf(W)==-1}catch(a){}A=function(){return b};return b}
function B(){if(p&&q){var b=m.getElementById(Q);var c=b.contentWindow;if(A()){c.__gwt_getProperty=function(a){return H(a)}}proposals_module=null;c.gwtOnLoad(y,Q,s,x);n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:X,millis:(new Date).getTime(),type:Y})}}
function C(){function e(a){var b=a.lastIndexOf(Z);if(b==-1){b=a.length}var c=a.indexOf($);if(c==-1){c=a.length}var d=a.lastIndexOf(_,Math.min(c,b));return d>=0?a.substring(0,d+1):P}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=m.createElement(ab);b.src=a+bb;a=e(b.src)}return a}
function g(){var a=F(cb);if(a!=null){return a}return P}
function h(){var a=m.getElementsByTagName(db);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(eb)!=-1){return e(a[b].src)}}return P}
function i(){var a;if(typeof isBodyLoaded==fb||!isBodyLoaded()){var b=gb;var c;m.write(hb+b+ib);c=m.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=jb){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return P}
function j(){var a=m.getElementsByTagName(kb);if(a.length>0){return a[a.length-1].href}return P}
var k=g();if(k==P){k=h()}if(k==P){k=i()}if(k==P){k=j()}if(k==P){k=e(m.location.href)}k=f(k);s=k;return k}
function D(){var b=document.getElementsByTagName(lb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(mb),g;if(f){f=f.replace(nb,P);if(f.indexOf(ob)>=0){continue}if(f==pb){g=e.getAttribute(qb);if(g){var h,i=g.indexOf(rb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=P}t[f]=h}}else if(f==sb){g=e.getAttribute(qb);if(g){try{z=eval(g)}catch(a){alert(tb+g+ub)}}}else if(f==vb){g=e.getAttribute(qb);if(g){try{y=eval(g)}catch(a){alert(tb+g+wb)}}}}}}
function E(a,b){return b in u[a]}
function F(a){var b=t[a];return b==null?null:b}
function G(a,b){var c=w;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
function H(a){var b=v[a](),c=u[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(z){z(a,d,b)}throw null}
var I;function J(){if(!I){I=true;var a=m.createElement(xb);a.src=yb;a.id=Q;a.style.cssText=zb;a.tabIndex=-1;m.body.appendChild(a);n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:X,millis:(new Date).getTime(),type:Ab});a.contentWindow.location.replace(s+L)}}
v[Bb]=function(){var b=null;var c=Cb;try{if(!b){var d=location.search;var e=d.indexOf(Db);if(e>=0){var f=d.substring(e+7);var g=d.indexOf(Eb,e);if(g<0){g=d.length}b=d.substring(e+7,g)}}if(!b){b=F(Bb)}if(!b){b=l[Fb]}if(b){c=b}while(b&&!E(Bb,b)){var h=b.lastIndexOf(Gb);if(h<0){b=null;break}b=b.substring(0,h)}}catch(a){alert(Hb+a)}l[Fb]=c;return b||Cb};u[Bb]={de_CH:0,de_DE:1,'default':2,en_GB:3,en_UK:4,fr:5,fr_CA:6,fr_CH:7,fr_FR:8,hu_HU:9,it_CH:10,it_IT:11,pl_PL:12,pt_BR:13,pt_PT:14};proposals_module.onScriptLoad=function(){if(I){q=true;B()}};proposals_module.onInjectionDone=function(){p=true;n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:Ib,millis:(new Date).getTime(),type:Y});B()};D();C();var K;var L;if(A()){if(l.external&&(l.external.initModule&&l.external.initModule(Q))){l.location.reload();return}L=Jb;K=P}n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:Kb});if(!A()){try{G([Lb],Mb);G([Nb],Ob);G([Cb],Pb);G([Qb],Rb);G([Sb],Tb);G([Ub],Vb);G([Wb],Xb);G([Yb],Zb);G([$b],_b);G([ac],bc);G([cc],dc);G([ec],fc);G([gc],hc);G([ic],jc);G([kc],lc);K=w[H(Bb)];var M=K.indexOf(mc);if(M!=-1){x=Number(K.substring(M+1));K=K.substring(0,M)}L=K+nc}catch(a){return}}var N;function O(){if(!r){r=true;if(!__gwt_stylesLoaded[oc]){var a=m.createElement(pc);__gwt_stylesLoaded[oc]=a;a.setAttribute(qc,rc);a.setAttribute(sc,s+oc);m.getElementsByTagName(tc)[0].appendChild(a)}if(!__gwt_stylesLoaded[uc]){var a=m.createElement(pc);__gwt_stylesLoaded[uc]=a;a.setAttribute(qc,rc);a.setAttribute(sc,s+uc);m.getElementsByTagName(tc)[0].appendChild(a)}B();if(m.removeEventListener){m.removeEventListener(vc,O,false)}if(N){clearInterval(N)}}}
if(m.addEventListener){m.addEventListener(vc,function(){J();O()},false)}var N=setInterval(function(){if(/loaded|complete/.test(m.readyState)){J();O()}},50);n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:Y});n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:Ib,millis:(new Date).getTime(),type:T});m.write(wc)}
proposals_module();